"""
Django settings for iambd project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import environ
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR,'file.env'))
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')



# Quick-start development settings - 
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v=@*zbkjfqcem@n^hu=t6p^kkn2qcge9hdj*b%ia946-uqg1wu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ["iamabrandthebook.com", "www.iamabrandthebook.com"]
CSRF_TRUSTED_ORIGINS = [
    "https://iamabrandthebook.com",
    "https://www.iamabrandthebook.com"
]



AUTH_USER_MODEL = "accounts.CustomUser"


INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "django.contrib.sitemaps",
    "django.contrib.sites",
    'accounts',
    'paystack',
    'anymail',
 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iambd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'core/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iambd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),  
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/




# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'core/static',
]
# STATIC_ROOT is fine as is, WhiteNoise will manage this during deployment.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded content)
MEDIA_URL = '/media/'

# Check if the app is running on Railway (or another production environment)
if os.environ.get('ON_RAILWAY') == 'true':
    # 🌟 PRODUCTION SETTING: Use the ABSOLUTE path for the Railway Volume mount.
    # Assuming Railway places your project in /app, your media is at /app/core/media.
    MEDIA_ROOT = '/app/core/media'
else:
    # DEVELOPMENT SETTING: Your current local path.
    MEDIA_ROOT = BASE_DIR / 'core/media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# emaill config

EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER')
ADMIN_EMAIL = env('ADMIN_EMAIL')

load_dotenv()  # only needed if you’re using a .env file locally

PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')



RESEND_API_KEY = os.getenv("RESEND_API_KEY")

if not RESEND_API_KEY:
    print("❌ RESEND_API_KEY not found in environment!")
else:
    print("✅ RESEND_API_KEY loaded successfully")



# SITE_URL = "http://127.0.0.1:8000" 
SITE_URL = "https://iamabrandthebook.com"

# Optional: Verify that both exist
if not PAYSTACK_PUBLIC_KEY:
    print("⚠️ PAYSTACK_PUBLIC_KEY not found in environment!")




UNFOLD = {
    "SITE_HEADER": "IAmABrand Admin",
    "SITE_TITLE": "IAmABrand Admin Panel",
    "SITE_SUBHEADER": "Bookshop by Kevwe Modupe",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("assets/images/logo.png"),
        "dark": lambda request: static("assets/images/logo_white.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("assets/images/logo.png"),
        "dark": lambda request: static("assets/images/logo_white.png"),
    },
    "DASHBOARD": {
        "show_search": True,
        "show_all_applications": True,
        "cards": [
            {
                "title": _("Users"),
                "icon": "group",
                "link": reverse_lazy("admin:accounts_customuser_changelist"),
                "description": _("Manage registered users."),
            },
            {
                "title": _("Blog Posts"),
                "icon": "article",
                "link": reverse_lazy("admin:accounts_blogpost_changelist"),
                "description": _("Manage blog posts."),
            },
            {
                "title": _("Blog Content"),
                "icon": "notes",
                "link": reverse_lazy("admin:accounts_blogcontent_changelist"),
                "description": _("Manage blog post sections."),
            },
            {
                "title": _("Sales Counter"),
                "icon": "bar_chart",
                "link": reverse_lazy("admin:accounts_salescounter_changelist"),
                "description": _("Track sales counters."),
            },
            {
                "title": _("User Sales"),
                "icon": "shopping_cart",
                "link": reverse_lazy("admin:accounts_usersale_changelist"),
                "description": _("Track sales by user and page."),
            },
        ],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Management"),
                "icon": "store",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_customuser_changelist"),
                    },
                    {
                        "title": _("Blog Posts"),
                        "icon": "article",
                        "link": reverse_lazy("admin:accounts_blogpost_changelist"),
                    },
                    {
                        "title": _("Blog Content"),
                        "icon": "notes",
                        "link": reverse_lazy("admin:accounts_blogcontent_changelist"),
                    },
                    {
                        "title": _("Sales Counter"),
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin:accounts_salescounter_changelist"),
                    },
                    {
                        "title": _("User Sales"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:accounts_usersale_changelist"),
                    },
                ],
            },
        ],
    },
}
