# Generated by Django 5.2.4 on 2025-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_copy_sold', models.IntegerField(default=0)),
                ('hard_copy_sold', models.IntegerField(default=10)),
            ],
        ),
    ]
