# Generated by Django 5.2.4 on 2025-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersale',
            name='user',
        ),
        migrations.AddField(
            model_name='usersale',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usersale',
            name='referring_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersale',
            name='page_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
